[package]
name = "mongowner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongododm = { path = "../mongododm-rs"}
quote = "1.0"
syn = "2.0"

[lib]
proc_macro = true
